set_album:
  fields:
    device_id:
      required: false
      selector:
        text:
    album_id:
      required: false
      selector:
        text:
    album_ids:
      required: false
      selector:
        object:
    album_name:
      required: false
      selector:
        text:
    album_names:
      required: false
      selector:
        object:

set_profile:
  fields:
    device_id:
      required: false
      selector:
        text:
    profile_id:
      required: true
      selector:
        text:

refresh_albums:
  fields:
    device_id:
      required: false
      selector:
        text:

set_renderer_options:
  fields:
    device_id:
      required: false
      selector:
        text:
    durationSeconds:
      required: false
      selector:
        number:
          min: 5
          max: 3600
          unit_of_measurement: s
    imageFit:
      required: false
      selector:
        select:
          options:
            - contain
            - cover
            - none
    showTime:
      required: false
      selector:
        boolean:
    timeFormat:
      required: false
      selector:
        select:
          options:
            - "24"
            - "12"
    showAmPm:
      required: false
      selector:
        boolean:
    showSeconds:
      required: false
      selector:
        boolean:
    showDate:
      required: false
      selector:
        boolean:
    dateFormat:
      required: false
      selector:
        text:
    clockSource:
      required: false
      selector:
        select:
          options:
            - client
            - server
    showWeather:
      required: false
      selector:
        boolean:
    weatherLocation:
      required: false
      selector:
        text:
    weatherRotationInterval:
      required: false
      selector:
        number:
          min: 10
          max: 3600
          step: 1
          unit_of_measurement: s
    showVideos:
      required: false
      selector:
        boolean:
    showArchived:
      required: false
      selector:
        boolean:
    filterDate:
      required: false
      selector:
        text:
    filterNewest:
      required: false
      selector:
        number:
          min: 0
          max: 50000
          step: 1
    albumOrder:
      required: false
      selector:
        select:
          options:
            - random
            - newest
            - oldest
    transition:
      required: false
      selector:
        select:
          options:
            - none
            - fade
            - cross-fade
    fadeTransitionDuration:
      required: false
      selector:
        number:
          min: 0
          max: 20
          step: 0.5
          unit_of_measurement: s
    crossFadeTransitionDuration:
      required: false
      selector:
        number:
          min: 0
          max: 20
          step: 0.5
          unit_of_measurement: s
    layout:
      required: false
      selector:
        select:
          options:
            - single
            - portrait
            - landscape
            - splitview
            - splitview-landscape
    imageEffect:
      required: false
      selector:
        select:
          options:
            - none
            - zoom
            - smart-zoom
    imageEffectAmount:
      required: false
      selector:
        number:
          min: 100
          max: 1000
          step: 10
    backgroundBlur:
      required: false
      selector:
        boolean:
    backgroundBlurAmount:
      required: false
      selector:
        number:
          min: 0
          max: 100
          step: 1
    fontSize:
      required: false
      selector:
        number:
          min: 50
          max: 250
          step: 1
          unit_of_measurement: "%"
    frameless:
      required: false
      selector:
        boolean:
    disableNavigation:
      required: false
      selector:
        boolean:
    hideCursor:
      required: false
      selector:
        boolean:
    showProgressBar:
      required: false
      selector:
        boolean:
    progressBarPosition:
      required: false
      selector:
        select:
          options:
            - top
            - bottom
    showImageRating:
      required: false
      selector:
        boolean:
    showOwner:
      required: false
      selector:
        boolean:
    showAlbumName:
      required: false
      selector:
        boolean:
    showPersonName:
      required: false
      selector:
        boolean:
    showPersonAge:
      required: false
      selector:
        boolean:
    showImageTime:
      required: false
      selector:
        boolean:
    imageTimeFormat:
      required: false
      selector:
        select:
          options:
            - "24"
            - "12"
    showImageDate:
      required: false
      selector:
        boolean:
    imageDateFormat:
      required: false
      selector:
        text:
    showImageDescription:
      required: false
      selector:
        boolean:
    showImageCamera:
      required: false
      selector:
        boolean:
    showImageExif:
      required: false
      selector:
        boolean:
    showImageLocation:
      required: false
      selector:
        boolean:
    showImageQr:
      required: false
      selector:
        boolean:
    showImageId:
      required: false
      selector:
        boolean:
    showUser:
      required: false
      selector:
        boolean:
    showMoreInfo:
      required: false
      selector:
        boolean:
    burnInInterval:
      required: false
      selector:
        number:
          min: 0
          max: 1440
          unit_of_measurement: min
    burnInDuration:
      required: false
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: s
    burnInOpacity:
      required: false
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    sleepStart:
      required: false
      selector:
        text:
    sleepEnd:
      required: false
      selector:
        text:
    sleepIcon:
      required: false
      selector:
        boolean:
    sleepDimScreen:
      required: false
      selector:
        boolean:
    disableSleep:
      required: false
      selector:
        boolean:

set_network_mode:
  fields:
    device_id:
      required: false
      selector:
        text:
    network_mode:
      required: true
      selector:
        select:
          options:
            - auto
            - local
            - external
