set_album:
  fields:
    device_id:
      required: false
      selector:
        text:
    album_id:
      required: false
      selector:
        text:
    album_ids:
      required: false
      selector:
        object:

set_profile:
  fields:
    device_id:
      required: false
      selector:
        text:
    profile_id:
      required: true
      selector:
        text:

refresh_albums:
  fields:
    device_id:
      required: false
      selector:
        text:

set_renderer_options:
  fields:
    device_id:
      required: false
      selector:
        text:
    durationSeconds:
      required: false
      selector:
        number:
          min: 5
          max: 3600
          unit_of_measurement: s
    imageFit:
      required: false
      selector:
        select:
          options:
            - contain
            - cover
            - none
    showTime:
      required: false
      selector:
        boolean:
    showDate:
      required: false
      selector:
        boolean:
    showWeather:
      required: false
      selector:
        boolean:
    albumOrder:
      required: false
      selector:
        select:
          options:
            - random
            - newest
            - oldest

set_network_mode:
  fields:
    device_id:
      required: false
      selector:
        text:
    network_mode:
      required: true
      selector:
        select:
          options:
            - auto
            - local
            - external
