import type { AlbumCache, FrameDevice, FrameProfile, FrameState, PersonCache, StoreData } from './types.js';

export function createDefaultFrameState(device: FrameDevice): FrameState {
  return {
    deviceId: device.id,
    activeAlbumIds: [],
    activePersonIds: [],
    requireAllPeople: false,
    durationSeconds: 60,
    imageFit: 'contain',
    showTime: false,
    timeFormat: '24',
    showAmPm: true,
    showSeconds: false,
    showDate: false,
    dateFormat: 'YYYY/MM/DD',
    clockSource: 'client',
    showWeather: true,
    weatherLocation: '',
    weatherRotationInterval: 60,
    weatherShowForecast: 'inherit',
    weatherShowHumidity: 'inherit',
    weatherShowWind: 'inherit',
    weatherShowWindDirection: 'inherit',
    weatherShowVisibility: 'inherit',
    weatherShowTemperatureRange: 'inherit',
    weatherRoundTemperature: 'inherit',
    showVideos: false,
    kioskVideoMuted: true,
    excludeVideosOver: 0,
    showArchived: false,
    filterDate: '',
    filterNewest: 0,
    upArrowAction: 'mute',
    downArrowAction: 'none',
    albumOrder: 'random',
    networkMode: device.networkMode,
    transition: 'none',
    fadeTransitionDuration: 1,
    crossFadeTransitionDuration: 1,
    layout: 'single',
    imageEffect: 'none',
    imageEffectAmount: 120,
    backgroundBlur: true,
    backgroundBlurAmount: 10,
    fontSize: 100,
    frameless: false,
    disableNavigation: false,
    hideCursor: true,
    showProgressBar: false,
    progressBarPosition: 'top',
    showImageRating: false,
    showOwner: false,
    showAlbumName: false,
    showPersonName: false,
    showPersonAge: false,
    showImageTime: false,
    imageTimeFormat: '24',
    showImageDate: false,
    imageDateFormat: 'YYYY-MM-DD',
    showImageDescription: false,
    imageDescriptionScrollDuration: 52,
    imageDescriptionScrollSpeed: 2.5,
    imageDescriptionStartDelay: 3,
    imageDescriptionAreaHeight: 5.75,
    imageDescriptionOverlayOpacity: 10,
    imageDescriptionLongThresholdLines: 3.25,
    showImageCamera: false,
    showImageExif: false,
    showImageLocation: false,
    showImageQr: false,
    showImageId: false,
    showUser: false,
    showMoreInfo: true,
    burnInInterval: 0,
    burnInDuration: 30,
    burnInOpacity: 30,
    sleepStart: '',
    sleepEnd: '',
    sleepIcon: true,
    sleepDimScreen: false,
    disableSleep: false,
    version: 1,
    updatedAt: new Date().toISOString(),
  };
}

export function createDefaultProfiles(): Record<string, FrameProfile> {
  return {
    default: {
      id: 'default',
      name: 'Default',
      albumIds: [],
      personIds: [],
      requireAllPeople: false,
      durationSeconds: 60,
      imageFit: 'contain',
      showTime: false,
      timeFormat: '24',
      showAmPm: true,
      showSeconds: false,
      showDate: false,
      dateFormat: 'YYYY/MM/DD',
      clockSource: 'client',
      showWeather: true,
      weatherLocation: '',
      weatherRotationInterval: 60,
      weatherShowForecast: 'inherit',
      weatherShowHumidity: 'inherit',
      weatherShowWind: 'inherit',
      weatherShowWindDirection: 'inherit',
      weatherShowVisibility: 'inherit',
      weatherShowTemperatureRange: 'inherit',
      weatherRoundTemperature: 'inherit',
      showVideos: false,
      excludeVideosOver: 0,
      showArchived: false,
      filterDate: '',
      filterNewest: 0,
      albumOrder: 'random',
      preferredNetworkMode: 'auto',
      transition: 'none',
      fadeTransitionDuration: 1,
      crossFadeTransitionDuration: 1,
      layout: 'single',
      imageEffect: 'none',
      imageEffectAmount: 120,
      backgroundBlur: true,
      backgroundBlurAmount: 10,
      fontSize: 100,
      frameless: false,
      disableNavigation: false,
      hideCursor: true,
      showProgressBar: false,
      progressBarPosition: 'top',
      showImageRating: false,
      showOwner: false,
      showAlbumName: false,
      showPersonName: false,
      showPersonAge: false,
      showImageTime: false,
      imageTimeFormat: '24',
      showImageDate: false,
      imageDateFormat: 'YYYY-MM-DD',
      showImageDescription: false,
      imageDescriptionScrollDuration: 52,
      imageDescriptionScrollSpeed: 2.5,
      imageDescriptionStartDelay: 3,
      imageDescriptionAreaHeight: 5.75,
      imageDescriptionOverlayOpacity: 10,
      imageDescriptionLongThresholdLines: 3.25,
      showImageCamera: false,
      showImageExif: false,
      showImageLocation: false,
      showImageQr: false,
      showImageId: false,
      showUser: false,
      showMoreInfo: true,
      burnInInterval: 0,
      burnInDuration: 30,
      burnInOpacity: 30,
      sleepStart: '',
      sleepEnd: '',
      sleepIcon: true,
      sleepDimScreen: false,
      disableSleep: false,
    },
  };
}

export function createEmptyAlbumCache(): AlbumCache {
  return {
    items: [],
    stale: true,
  };
}

export function createEmptyPersonCache(): PersonCache {
  return {
    items: [],
    stale: true,
  };
}

export function createDefaultStore(device: FrameDevice): StoreData {
  return {
    devices: {
      [device.id]: device,
    },
    frames: {
      [device.id]: createDefaultFrameState(device),
    },
    profiles: createDefaultProfiles(),
    albumCache: createEmptyAlbumCache(),
    personCache: createEmptyPersonCache(),
    frameClaims: {},
    auth: {
      tokens: {},
    },
  };
}
